<a href="https://colab.research.google.com/github/tuannguyen1291/Vecto/blob/main/Bt_vecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Câu 1:

In [ ]:
x=abs(int(input("Nhập vào x: ")))
A=[]
for i in range (0,x+1):
  if x!=7:
    x=abs(int(input("Nhập lại x: ")))
  A.append(i)
print(A)

Nhập vào x: 6
Nhập lại x: 7
[0, 1, 2, 3, 4, 5, 6]


##Câu 2:

In [ ]:
#Thư viện random
import random
A=[]
for i in range(1,31):
 A.append(random.randint(-10,10))
print(A)

[-10, 3, 0, 1, 7, -7, 5, 6, 1, 3, -7, 7, 7, -8, -3, -8, 1, 5, 4, 0, 1, -1, -5, -2, -3, 9, -3, -1, -5, 0]


##Câu 3

In [ ]:
#thư viện random
import random
A=[]
for i in range(0,30):
  A.append(random.uniform(-5.7,6.9))
print(A)

[-3.6495561933018634, 3.9496170422890815, 2.1985482039272704, -5.077393681370365, 0.512716033028064, 1.751915732413826, 6.059918221468712, -2.173476735330039, 5.873500164443807, 0.23710980130699966, -0.7749152924899949, -2.535681195211342, 6.474118187843831, 5.883606975233209, -2.190112978847444, -0.38637128517695896, 3.314954764122482, 2.9437259165623244, 3.0062627648976052, 0.48442389633427574, -1.7907186618747537, 4.1119547083621955, 3.581897160699792, -1.9701686664212565, -0.7025198578905654, -1.5109670624592377, 2.3380593763730433, -4.410908660570403, 4.466786112375581, -4.492129101750568]


##Câu4

In [ ]:
import numpy as np
a = int(input("Nhập phần tử của a = "))
x=np.random.randint(-10,10,(1,11))
y=x*a
print(x)
print(y)

Nhập phần tử của a = 2
[[-3  3  4  2  5  0  8 -1 -5 -2 -9]]
[[ -6   6   8   4  10   0  16  -2 -10  -4 -18]]


##Câu 5

In [ ]:
import numpy as np
x=np.random.randint(-10,10,(1,16))
y=np.random.randint(-10,10,(1,16))
print(x)
print(y)    
print(x+y)
print(x-y)

[[  6  -4  -4   8  -6   6   7   6   5  -9   8  -9  -1  -3 -10   9]]
[[ 9  7  5 -6  4  7 -4 -8  5  2  9 -6 -3  8 -6  9]]
[[ 15   3   1   2  -2  13   3  -2  10  -7  17 -15  -4   5 -16  18]]
[[ -3 -11  -9  14 -10  -1  11  14   0 -11  -1  -3   2 -11  -4   0]]


## Câu6

In [ ]:
import numpy as np
x=np.random.randint(-10, 10,(1,11))
y=np.random.randint(-10,10,(1,11))
z=np.multiply(x,y)
print(x)
print(y)
print(z)

[[ 3 -8  8  6 -9  0  8  3  8  5  5]]
[[ -6   4   8  -5  -2 -10  -9   1  -1  -4  -8]]
[[-18 -32  64 -30  18   0 -72   3  -8 -20 -40]]


##Câu 7: Tính tích vô hướng hai vecto

In [ ]:
import random
x = []
y = []
TVH = 0 
for i in range (0,10,1):
    x.append(random.randint(-10,10))
    y.append(random.randint(-10,10))
    TVH=TVH+(x[i]*y[i])
print(x)
print(y)
print(TVH)

[0, -5, 5, 5, 8, 1, 0, -1, -5, -10]
[4, 4, 5, -6, 2, -5, 5, 0, 3, -8]
51


##Câu 8: Sinh ngẫu nhiên ma trận, in phần tử a23

In [ ]:
import numpy as np
_A=np.random.randint(-10,10,(3,5))
print("Ma trận A là: ")
for doing in _A:
  for element in doing:
    print(element,end=" ")
  print()
print("Giá trị của a23:")
print(_A[1,2])

Ma trận A là: 
7 8 6 -5 -2 
-1 -2 -1 -9 -9 
8 4 8 0 -6 
Giá trị của a23:
-1


##Câu 9:nhân vô hướng

In [ ]:
import numpy as np
a=int(input("Nhập hệ số tự do: "))
_A=np.random.randint(-10,10,(3,5))
print("Ma trận A là: ")
for doing in _A:
  for element in doing:
    print(element,end=" ")
  print()
A=np.array(_A)
X=a*A
print("Ma trận a*A là: ")
for doing in X:
  for element in doing:
    print(element,end=" ")
  print()

Nhập hệ số tự do: 5
Ma trận A là: 
-10 7 2 5 -9 
-2 -3 7 7 8 
-4 -8 -2 -8 3 
Ma trận a*A là: 
-50 35 10 25 -45 
-10 -15 35 35 40 
-20 -40 -10 -40 15 


##Câu 10: Phép cộng hai ma trận

In [ ]:
import numpy as np
_A=np.random.randint(-5,5,(3,5))
print("Ma trận A là: ")
for doing in _A:
  for element in doing:
    print(element,end=" ")
  print()
_B=np.random.randint(-5,5,(3,5))
print("Ma trận B là: ")
for doing in _B:
  for element in doing:
    print(element,end=" ")
  print()
A=np.array(_A)
B=np.array(_B)
C=A+B
print("Ma trận A + B là: ")
for doing in C:
  for element in doing:
    print(element,end=" ")
  print()

Ma trận A là: 
4 3 0 1 -5 
1 -3 3 -2 -4 
-4 -1 -4 0 1 
Ma trận B là: 
3 2 4 0 -2 
-4 -4 2 -5 4 
-2 -1 4 -5 -4 
Ma trận A + B là: 
7 5 4 1 -7 
-3 -7 5 -7 0 
-6 -2 0 -5 -3 


## Câu 11: Phép nhân hai ma trận 

In [ ]:
import numpy as np
_A=np.random.randint(-10,10,(3,4))
print("Ma trận A là: ")
for doing in _A:
  for element in doing:
    print(element,end=" ")
  print()
_B=np.random.randint(-10,10,(4,5))
print("Ma trận B là: ")
for doing in _B:
  for element in doing:
    print(element,end=" ")
  print()
A=np.array(_A)
B=np.array(_B)
C=A.dot(B)
print("Hai ma trận nhân nhau: ")
for doing in C:
  for element in doing:
    print(element,end=" ")
  print()

Ma trận A là: 
9 -7 6 8 
0 -4 1 -1 
2 1 9 2 
Ma trận B là: 
6 -1 -2 -10 -7 
3 0 -6 -2 -6 
-5 -1 4 1 8 
7 -3 -1 -10 -5 
Hai ma trận nhân nhau: 
59 -39 40 -150 -13 
-24 2 29 19 37 
-16 -17 24 -33 42 
