<a href="https://colab.research.google.com/github/tuannguyen1291/Vecto/blob/main/Bt_vecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Câu 1:

In [ ]:
x=abs(int(input("Nhập vào x: ")))
A=[]
for i in range (0,x+1):
  if x!=7:
    x=abs(int(input("Nhập lại x: ")))
  A.append(i)
print("Ma trận là:")
print(A)

Nhập vào x: 7
Ma trận là:
[0, 1, 2, 3, 4, 5, 6, 7]


##Câu 2:

In [ ]:
#Thư viện random
import random
A=[]
for i in range(1,31):
 A.append(random.randint(-10,10))
print("Ma trận là:")
print(A)

Ma trận là:
[-3, -1, 1, 2, -7, -1, 7, -1, 10, 5, -9, 4, -10, 2, 5, 8, -4, 2, -10, -9, 9, -1, -10, 8, 10, 9, 4, 0, 3, 5]


##Câu 3

In [ ]:
#thư viện random
import random
A=[]
for i in range(0,30):
  A.append(random.uniform(-5.7,6.9))
print("Ma trận là:")
print(A)

Ma trận là:
[3.4513722690890196, -1.0806408738227047, -5.162974330401609, -4.1011491689313715, -0.5971464253428813, -0.9110705453079779, -1.6266872114861943, -2.6337747868413093, 3.15526083924155, -2.759242984110478, 1.420955232133207, 0.17706086296347312, -5.3461072535662995, 5.996026779584789, -5.593227968218501, -3.318409300294148, -1.4629029346824174, -0.7456262890303123, 5.035498027911561, 2.0243873003154977, 6.085324848724395, -2.021295076332911, -4.292868533491751, -0.17880577595511937, 4.040825700400709, 2.822289697026773, 0.6447472670424386, -1.126917670088032, 6.368846307887439, -1.9083245155759427]


##Câu4

In [ ]:
import random
import numpy as np
a = int(input("Nhập phần tử của a = "))
x=[random.randint(-10,10) for i in range(1,11)]
print("Ma trận là:")
print(x)
x=np.array(x)
y=x*a
print("Ma trận nhân là:")
print(y)

Nhập phần tử của a = 2
Ma trận là:
[-1, 10, 1, -7, -2, -7, -4, 9, 3, -1]
Ma trận nhân là:
[ -2  20   2 -14  -4 -14  -8  18   6  -2]


##Câu 5

In [ ]:
import numpy as np
import random
x=[random.randint(-10,10) for i in range(1,16)]
y=[random.randint(-10,10) for i in range(1,16)]
x=np.array(x)
y=np.array(y)
print("Ma trận 1:")
print(x)
print("Ma trận 2:")
print(y)   
print(" Hai ma trận cộng:") 
print(x+y)
print("Hai ma trận nhân:")
print(x-y)

Ma trận 1
[ 1  5 -6 -9 -9  3  4  8 -3 -3 -6 -6 -2  3 -3]
Ma trận 2
[-8  5  5  1 -5  5  9  2 -1 -6  3 -2  0 -1 -6]
 Hai ma trận cộng
[ -7  10  -1  -8 -14   8  13  10  -4  -9  -3  -8  -2   2  -9]
Hai ma trận nhân
[  9   0 -11 -10  -4  -2  -5   6  -2   3  -9  -4  -2   4   3]


## Câu6

In [12]:
import numpy as np
x=np.random.randint(-10, 10,(1,11))
y=np.random.randint(-10,10,(1,11))
z=np.multiply(x,y)
print("Ma trận 1 là:")
print(x)
print("Ma trận 2 là:")
print(y)
print("Ma trận 1 x Ma trận 2")
print(z)

Ma trận 1 là:
[[  4   1   5  -2  -6   4 -10   2   2   7   4]]
Ma trận 2 là:
[[-10  -5   5   3   1  -2  -1   0  -2   3 -10]]
Ma trận 1 x Ma trận 2
[[-40  -5  25  -6  -6  -8  10   0  -4  21 -40]]


##Câu 7: Tính tích vô hướng hai vecto

In [ ]:
import random
x = []
y = []
TVH = 0 
for i in range (0,10):
    x.append(random.randint(-10,10))
    y.append(random.randint(-10,10))
    TVH=TVH+(x[i]*y[i])
print("Ma trận 1:",x)
print("Ma trận 2:",y)
print("Tích vô hướng bằng",TVH)

Ma trận 1: [-8, 5, -2, -6, 9, -9, 9, 8, -6, 3]
Ma trận 2: [2, -6, 4, -1, -10, 4, -10, 4, -10, 6]
Tích vô hướng bằng -154


##Câu 8: Sinh ngẫu nhiên ma trận, in phần tử a23

In [ ]:
import numpy as np
A=np.random.randint(-10,10,(3,5))
print("Ma trận A là: ",A)
print("Giá trị của a23:")
print(A[1,2])

Ma trận A là:  [[ 7  1 -9  6  3]
 [ 6  6  9 -7 -8]
 [-8 -6  0 -7  5]]
Giá trị của a23:
9


##Câu 9:nhân vô hướng

In [ ]:
import numpy as np
a=int(input("Nhập hệ số tự do: "))
A=np.random.randint(-10,10,(3,5))
print("Ma trận A là: ",A)
A=np.array(A)
X=a*A
print("Ma trận a*A là: ",X)

Nhập hệ số tự do: 3
Ma trận A là:  [[  5   8  -3  -2   1]
 [-10  -3  -6  -4   9]
 [ -4   1  -3   6  -4]]
Ma trận a*A là:  [[ 15  24  -9  -6   3]
 [-30  -9 -18 -12  27]
 [-12   3  -9  18 -12]]


##Câu 10: Phép cộng hai ma trận

In [ ]:
import numpy as np
A=np.random.randint(-5,5,(3,5))
print("Ma trận A là: ",A)
B=np.random.randint(-5,5,(3,5))
print("Ma trận B là: ",B)
A=np.array(A)
B=np.array(B)
C=A+B
print("Ma trận A + B là: ",C)

Ma trận A là:  [[-1  3 -5 -2  4]
 [ 1 -3 -4  3 -2]
 [ 2 -5  4 -2  4]]
Ma trận B là:  [[ 3  1 -2  4  4]
 [-5  1  4 -1 -5]
 [-2 -4  1  3 -5]]
Ma trận A + B là:  [[ 2  4 -7  2  8]
 [-4 -2  0  2 -7]
 [ 0 -9  5  1 -1]]


## Câu 11: Phép nhân hai ma trận 

In [ ]:
import numpy as np
A=np.random.randint(-10,10,(3,4))
print("Ma trận A là:",A)
B=np.random.randint(-10,10,(4,5))
print("Ma trận B là:",B)
C=A.dot(B)
print("Hai ma trận nhân nhau:",C)

Ma trận A là: [[-6  3 -5 -6]
 [-9 -3  9 -2]
 [-9 -4  9 -6]]
Ma trận B là: [[ 0  8 -8  0 -1]
 [ 1 -6  4  0 -2]
 [-6 -1 -1 -5  1]
 [ 9  3  5  9 -8]]
Hai ma trận nhân nhau: [[ -21  -79   35  -29   43]
 [ -75  -69   41  -63   40]
 [-112  -75   17  -99   74]]
